spring.application.name=SmartHire

spring.datasource.url=jdbc:h2:file:./data/smarthire
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

jwt.secret=change-this-secret-to-at-least-32-characters
jwt.expiration-ms=86400000
